### ISSUE TITLE
'not one of the listed choices' error when in the middle of a calculation

### ISSUE THREAD

**Issue by mosgood549** [FB-18-19-PreAP-CS/math-helper-helenasimmons#4]
When I put in 3 and 4 in for the Pythagorean theorem, I got 5.0 and "That was not one of the listed choices". It didn't ask for c, and I guess that it interpreted 4 as my choice for the calculator. I suggest that you put a While true loop in the main function (for the initial calculator display) , and hopefully that might fix it.

**Comment by lcsimmons** [comment]
Fixed. Thank you :)
